// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bio: dynamic(() => import("./About")),
  hero: dynamic(() => import("./Hero")),
  marquee: dynamic(() => import("./Marquee")),
};
